config/routes.rb
Rails.application.routes.draw do
  get 'user_settings/index'
  get 'user_settings/create'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "user_settings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_setting.rb
class UserSetting < ApplicationRecord

end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  def index
    @setting = UserSetting.new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'TODO App', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
// もしユーザーがログインしているならば下記を表示
      <%  if user_signed_in?  %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
//ログインしていないのなら下記を表示
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniQuiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MiniQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MiniQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/settings/create.html.erb
<h1>Settings#create</h1>
<p>Find me in app/views/settings/create.html.erb</p>

app/views/user_settings/create.html.erb
<h1>UserSettings#create</h1>
<p>Find me in app/views/user_settings/create.html.erb</p>

app/views/user_settings/index.html.erb
<%= form_with url: user_settings_index_path do |f| %>
    <%= select_tag 'user_setting[difficulty]', options_for_select([["簡単", "easy"], ["普通", "normal"], ["難しい", "hard"]]) %>
    
<% end %>